module.exports = {
  slipe: require('@/assets/music/more-slipe.mp3'),
  advanced: require('@/assets/music/advanced.mp3'),
  oneSlow: require('@/assets/music/one-slow.mp3'),
  moreAdvanced: require('@/assets/music/more-advanced.mp3'),
  moreUsually: require('@/assets/music/more-usually.mp3'),
  flop: require('@/assets/music/flop.mp3'),
  flopAfter: require('@/assets/music/flop-after.mp3'),
  slipeStart: require('@/assets/music/more-slipe-start.mp3'), 
  EPIC1: require('@/assets/music/more-EPIC1.mp3'),
  EPIC2: require('@/assets/music/more-EPIC2.mp3'),
  EPIC3: require('@/assets/music/more-EPIC3.mp3'),
  LEGEND: require('@/assets/music/more-LEGEND.wav'),
  NORMAL1: require('@/assets/music/more-NORMAL1.mp3'),
  NORMAL2: require('@/assets/music/more-NORMAL2.mp3'),
  NORMAL3: require('@/assets/music/more-NORMAL3.mp3'),
  NORMAL4: require('@/assets/music/more-NORMAL4.mp3'),
  NORMAL5: require('@/assets/music/more-NORMAL5.mp3'),
};